/**
 * Typed shape of data/papers.json, generated by `npm run papers`.
 */
export type DocType = "qp" | "ms" | "er";

export interface PaperDoc {
  /** Absolute URL to the PDF on qualifications.pearson.com */
  url: string;
  /** true when Pearson gates the file behind sign-in (typically the most recent 12 months) */
  gated: boolean;
}

export interface Paper {
  /** Unit code, e.g. "WMA11" */
  code: string;
  /** Exam session month */
  session: "January" | "June" | "October";
  /** Exam year, 2019..2026 */
  year: number;
  /** "A"/"B" when a unit had multiple variants in one session */
  variant: string | null;
  qp: PaperDoc | null;
  ms: PaperDoc | null;
  er: PaperDoc | null;
}

export interface Unit {
  code: string;
  name: string;
  short: string;
  papers: Paper[];
}

export interface Subject {
  key: "mathematics" | "physics" | "chemistry" | "biology";
  label: string;
  units: Unit[];
}

export interface PapersData {
  generatedAt: string;
  yearMin: number;
  yearMax: number;
  subjects: Subject[];
}

import papersJson from "@/data/papers.json";

export const papersData = papersJson as unknown as PapersData;
